config/routes.rb
Rails.application.routes.draw do
  get 'item/index'

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @name = "Samuel"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/item/index.html.erb
<h1>List of items</h1>
<table>
    <tr><th>Name</th><th>Price</th></tr>
    <% @items.each do |item| %> 
        <tr><td><%= item.name %></td><td><%= item.price %></td></tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, <%= @name %>!</h1>
<p>This is a demonstration application in Ruby on Rails</p>
<%= link_to "List of items", item_index_path %>